### ISSUE TITLE
Connolly's bootstrap in rsad

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#15]
Include Connolly's et al. (2009, Ecology) bootstrap method in rsad.

**Comment by andrechalom** [comment]
For reference, the article cited is: http://www.jstor.org/discover/10.2307/25592854
Abstract:
Patterns in the commonness and rarity of species are a fundamental characteristic of ecological assemblages; however, testing between alternative models for such patterns remains an important challenge. Conventional approaches to fitting or testing species abundance models often assume that species, not individuals, are the units that are sampled and that species' abundances are independent of one another. Here we test three different models (the Poisson lognormal, the negative binomial, and the neutral, "zero-sum multinomial" [ZSM]) against species abundance distributions of Indo-Pacific corals and reef fishes. We derive and apply several alternative bootstrap analyses of model fit, each of which makes different assumptions about how species abundance data are sampled, and we assess the extent to which tests of model fit are sensitive to such assumptions. For all models, goodness of fit is remarkably consistent, regardless of whether one assumes that species or individuals are the units that are sampled or whether or not one assumes that species' abundances are statistically independent of one another. However, goodness-of-fit estimates are approximately twice as precise and detect lack of model fit more frequently, when based on sampling of individuals, rather than species. Bootstrap analyses indicate that the Poisson lognormal distribution exhibits substantially better fit to species abundance patterns, consistent with model selection analyses. In particular, heterogeneity in species abundances (many rare and few highly abundant species) is too great to be captured by the ZSM model or the negative binomial model and is best explained by models that predict species abundance patterns that are much closer, but not identical, to the lognormal distribution. More broadly, our bootstrap analyses suggest that estimates of model fit are likely to be robust to assumptions about the statistical interdependence of species abundances, but that tests of model fit are more powerful when they assume sampling of individuals, rather than species. Such individual-based tests therefore may be able to identify lack of model fit where previous tests have been inconclusive.

**Comment by andrechalom** [comment]
Most of the relevant information for our issue is at the appendix here: http://www.esapubs.org/archive/ecol/E090/225/appendix-A.htm

The first approach by Connolly et al. is to generate a sample of N species from the prescribed zero-truncated distribution. This was not comparable to our approach in `rsad`, as we did not have tools for zero-truncated random generators. Now this can be achieved with

```R
> rtrunc("ls", 100, coef=list(N=1000, alpha=50), trunc=5)
  [1]  7  8 10 35 16  7 14 11  9 19 10 32 15 12 11 46 18  6  7 10  8  6  6  6  9 48  8 11 14 17 13 11  6 28  6 68
 [37]  8 22 15  7  6 17  7 21 21 31 29 13  8  8 10  9 18 24  8 12 12 15 20 17 84 31  7  7 13 10  6  8 11 15  8 12
 [73]  6  7  8 17  6 43  8  9 40  6  7 31 12 26  6  6  8 34 10  6 13 13  9 13 11 15 61 50
> length(rtrunc("ls", 100, coef=list(N=1000, alpha=50), trunc=5))
[1] 100
```

I am also including the ability of selecting zero-truncated distributions on `rsad`, but it should be noted that because of the poisson sampling done afterwards, there is no guarantee that `rsad(S=100, etc etc)` will have 100 elements, even if frac=1:
```R
> length(rsad(100, frac=1, "lnorm", 1, meanlog=1, sdlog=1.8))
[1] 94
```

**Comment by andrechalom** [comment]
Discussion over this bootstrap methods have generated the issues #110 #111 #112 #113. We have already tools for generating two of the bootstrap samples proposed (species-based and Poisson individual-based), and probably nothing to gain by implementing the third (hypergeometric).
