### ISSUE TITLE
preston argument in octavpred

### ISSUE THREAD

**Issue by murilomiranda** [piLaboratory/sads#67]
We should include the preston argument in ocavpred as octav-function already has, then we could compare both methods.

**Comment by andrechalom** [comment]
OK, I'm working on this on the branch "preston", but I have a problem.

The code for computing Preston octaves, from `octav`, is:
```R
  N <- 2^(res$octave)
  j <- N[-length(N)]
  w <- y[y%in%j]
  ties <- table(factor(w, levels=j))
  res[-1, 3] <- res[-1, 3]+ties/2
  res[-length(N), 3] <- res[-length(N), 3]-ties/2
  return(res)
```

And it might work for `octavpred` when we pass a full fitted object, because we can extract "oct" and "y" from it. 

However, we also provide the interface `octavpred(object="missing",sad="character", rad="missing", coef="list", trunc="ANY", oct="numeric", S="numeric", N="numeric")`. In this case, I see no way of determining what "y" should be. Can you give me some pointers?

**Comment by andrechalom** [comment]
OK, after thiking a bit more about this, the "y" is used to determine the occurrences of y exactly equal to 2^N. When using "rad"s, this is possible to determine from inside the `octavpred` , but when using "sads" this make no sense, as the the predicted "y" are real numbers instead of integers, so maybe we should just issue a warning when the user selects "`preston=TRUE`" in calls using sads instead of rads and proceed as normal.

**Comment by piklprado** [comment]
Ok, but I think Preston's smoothing might be available also for discrete sad`s. In this case for objects of class `fitsad` what about calling `octav` on top of `radpred`? e.g.:
```r
> moths.ls <- fitsad(moths, "ls")
> octav(radpred(moths.ls)$abund, preston=TRUE)
Object of class "octav"
   octave upper Freq
1       0     1 20.0
2       1     2 30.0
3       2     4 28.0
4       3     8 28.5
5       4    16 26.5
6       5    32 26.5
7       6    64 25.0
8       7   128 21.5
9       8   256 18.0
10      9   512 11.0
11     10  1024  4.0
12     11  2048  1.0
13     12  4096  0.0
```

**Comment by piklprado** [comment]
By the way, we should solve this issue before merging PR #74 to master?

**Comment by andrechalom** [comment]
OK, I've run some tests comparing `octavpred` with `octav(radpred())`, without setting `preston=TRUE`, and they seem to have only very small differences, so I'm convinced that they are almost equivalent. 
![octavpred](https://cloud.githubusercontent.com/assets/1994997/10404621/47283d76-6eaa-11e5-88ca-802f795463d2.png)
(red: octavpred from fitbs(moths), green octav(radpred) for the same data) 

I'm creating a "switch" in the `octavpred` method for sads, that checks whether preston argument is set. If it is not, the original code is used. If it is set, we call `octav(radpred(...), preston=TRUE)`. An example of result is seen here:
![preston](https://cloud.githubusercontent.com/assets/1994997/10405080/0c6f8fba-6ead-11e5-9235-113b1434ccda.png)
(red: octavpred(fitbs(moths), preston=FALSE), blue: preston=TRUE)

There is only one last problem: `radpred` expects that we supply a "distr" argument, which **should** be deduced from the sad. I'll try to work on a replacement for this.

**Comment by piklprado** [comment]
Works ok to reproduce figure 1 from [Volkov et al (2003)](http://www.nature.com/nature/journal/v424/n6952/abs/nature01883.html). 

![bci_volkok_fig1](https://cloud.githubusercontent.com/assets/6313365/10561804/1e78cffe-7511-11e5-854f-2c30ca01a6b5.png)

```r
plot(octav( bci, preston = TRUE ))
bci.exp2 <- octavpred( bci, sad = "volkov",
                      coef = list(theta = 47.226, m = 0.1, J=sum(bci)), preston=TRUE)
lines( bci.exp2 )
``` 
But to do this  I have to change line 338 of the workhorse method for octavepred. This change probably changes preston binning for continuous distributions, but as the distr slot is deprecated by PR #86 I think this is not a problem.

**Comment by andrechalom** [comment]
Identical results from current distr branch.
